### ISSUE TITLE
Context reference date

### ISSUE THREAD

**Issue by hfinck** [tgallice/wit-php#17]
We should revise the implementation of the `reference_date` within the context. With the new wit.ai bot engine this field has no meaning anymore.

The current documentation suggests to either include a `reference_time` or `timezone` within the context to define the users time setting. [See here](https://wit.ai/docs/http/20160526#context-link)

We also need means of manipulating these settings, because right now this information is created implicitly with the server's time zone (which might not be the user's time zone).

What do you think? I suggest after these additions we create a new release, since all changes required to comply with the current wit.ai platform version are in place then.

**Comment by tgallice** [comment]
@hfinck yes we can improve this part. It's not require but I think is better to ensure a time reference than nothing. Currently we can set a custom `reference_date` directly be the constructor.

Have you some idea to improve it ?

**Comment by tgallice** [comment]
@hfinck I'm totaly wrong... I didn't get it that the field must be `reference_time` not `reference_date` ! I need to open my eyes.... We should definitly change this !

**Comment by hfinck** [comment]
I will open a pull request. Have most of this on my feature branch.

**Comment by tgallice** [comment]
@hfinck I did not see your message. I have already open a PR.
