### ISSUE TITLE
Get message back from converse

### ISSUE THREAD

**Issue by christophrumpel** [tgallice/wit-php#19]
Hey,

I am building a chatbot PHP boilerplate for starting building chatbots. I want to support different bot platforms like wit.ai and api.ai too.

So what I have is on central place where I receive the user's message. From there I provide several ways to "produce" an answer. One of them is with wit.ai. Another one is with custom code or with api.ai. But I need for all of them to get the message back.

With your sdk I can use the converse method but I do not get the message back, because the message is automatically send to the `say` method I need to extend in my action wrapper. Is there a chance to get the message back `from where I send the message`. Something similar like:

```
$context = $conversation->converse('session_id', $message);
$context->getMessage(); // what I would need
```

Or is this something you do not want or need?

**Comment by tgallice** [comment]
The `Conversation` class is just an implementation easly handle a full story of wit.ai. This class is juste based on the ConverseApi. You can make somethink like that :

```php

class CustomWit {
    private $api;

    public function __construct(ConverseApi $api) {
        $this->api = $api
    }

    public function getAnswer($message) {
        $response = $this->api->converse('sessionId', $message);
        return $response['type'] === 'msg' ? $response['msg'] : null;
    }
}

```
It's a naive implementation but it's give you an idea

**Comment by christophrumpel** [comment]
Thx that worked! Also using 3.1 now 👍 

Sometimes I get an error back like that:
````
{
    "confidence":1,
    "type":"error",
    "entities":{
        "my_method":[
            {"confidence":1,"type":"value","value":"My Value"}
        ]
    }
}
`````

So there is not msg inside, but I get my entities though it is type `error`.
Can I find somewhere what kind of error this is? Is it possible to get an error code or msg back?

Thx and greets
