### ISSUE TITLE
Converse

### ISSUE THREAD

**Issue by iboldurev** [tgallice/wit-php#2]
Please complete example for converse

How use ActionMapping (methods merge, stop)

**Comment by tgallice** [comment]
Hi @iboldurev 

Have you take a look at [tgallice/wit-php-example](https://github.com/tgallice/wit-php-example) ? The `ActionMapping` class is the extension point that you need to implement. 

You need to implement your own logic on it. The merge should return a merged context, based on what you get from the api. The say is trigger on a say action from the api etc...

The action method allow you to trigger your own custom method based on the action name.
