### ISSUE TITLE
Get action

### ISSUE THREAD

**Issue by christophrumpel** [tgallice/wit-php#23]
Hey,

I need to get an action that I defined for certain messages.
Is there an easy way in your package for this endpoint: https://wit.ai/docs/http/20160330#converse-link

I just want to provide the message and get the action without defining classes or methods.

Cheers

**Comment by tgallice** [comment]
You can use directly the `ConverseApi` class.
```php
$api = new ConverseApi($client);
$response = $api->converse($sessionId, 'my test');
```
`$response` is the decoded response from wit. This is what you want ?
