### ISSUE TITLE
Context is missing

### ISSUE THREAD

**Issue by AnonymousArthur** [tgallice/wit-php#25]
Context is empty when it's been set in previous dialogue.
Dialogue like this:
1.user: Send an email to AAA@BBB.COM
2.bot: What content do you want to send?
3.user: blah blah blah.
4.bot: email sent.

Email is been set in context at step 2, but it's missing at step 4 when controller received message. Please consider the dialogue is correctly set in Wit.ai

**Comment by tgallice** [comment]
Have you a mechanism to save/restore context between two calls ?

**Comment by AnonymousArthur** [comment]
No, isn't that done by Wit? For example it should automatically send the context to server based on given session id?

**Comment by AnonymousArthur** [comment]
I figured it out by saving context into local DB.
