### ISSUE TITLE
How to get confidence of action in conversation?

### ISSUE THREAD

**Issue by AnonymousArthur** [tgallice/wit-php#27]
Like the confidence value showing in Wit.ai Log tab, I want to response unknow message when the confidence is too low.

**Comment by tgallice** [comment]
If you use the `dev-master` version you can get the confidence from the step `$step->getConfidence()`. This feature was implemented here: https://github.com/tgallice/wit-php/pull/24/files 
If you have an older version take care to the BC.

**Comment by AnonymousArthur** [comment]
In the abstract class ActionMapping, I have action interface like this:
abstract public function action($sessionId, $actionName, Context $context, array $entities = []);
It doesn't have $step parameter. So weird.

**Comment by AnonymousArthur** [comment]
I see why, composer use 0.3.1 version which doesn't have this feature. I'll reinstall the package. Thank you very much!
