### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by beshoo** [tgallice/wit-php#3]
[root@server download]# composer require tgallice/wit-php

                                                                                                                                                    
  [InvalidArgumentException]                                                                                                                        
  Could not find package tgallice/wit-php at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
                                                                                                                                                    

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

[root@server download]# composer require tgallice/wit-php

                                                                                                                                                    
  [InvalidArgumentException]                                                                                                                        
  Could not find package tgallice/wit-php at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
                                                                                                                                                    

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

[root@server download]#

**Comment by tgallice** [comment]
When you have tried, none stable version of this library was release. It's the case now. You can retry It should be good.
