### ISSUE TITLE
Missing Tgallice\Wit\MessageApi;

### ISSUE THREAD

**Issue by usamanoman** [tgallice/wit-php#7]
Hi,

I installed the package through the composer. It's a very well written code, but you have missed to include MessageApi file when run through the composer. I have found these files in the repository so I am updating my code but for others it must auto install through composer.

**Comment by tgallice** [comment]
I have release the version `0.2.0` of this package which contains the new structure and api. Run `composer update tgallice/wit-php` to use the last version of the package. It's should not have BC break but if it's not, please open an issue.
