### ISSUE TITLE
example Conversation

### ISSUE THREAD

**Issue by jwasinski** [tgallice/wit-php#9]
Seem to be getting various errors when trying to create a simple Conversation class. It would be good to get a fully fleshed out example that doesn't require symphony.

**Comment by hfinck** [comment]
Can you provide some details? I didn't have any problems with the Conversation class.
Although there currently is a bug involving the say action. It does not execute converse again after the say command, so it does not receive the stop action from wit.ai. That does lead to unexpected result, but I have a fix ready.

**Comment by tgallice** [comment]
Hello @jwasinski. Like @hfinck if you can provide some details this will help us to help you. 
Basicaly you don't need to create a Conversation class. You just need to create an `ActionMapping` class like in the [wit-example][1] and create a [Conversation instance][2] with it. The `ActionMapping` handles the behavior of your application.

@hfinck You right with the say action issue. If you have already a fix, feel free to create a PR or I will do that today or tomorrow.

[1]: https://github.com/tgallice/wit-php-example/blob/master/src/Action/QuickAction.php
[2]: https://github.com/tgallice/wit-php-example/blob/master/src/Command/QuickstartCommand.php#L36-L37
